feat(): One day charts endpoint
f-pms/API pull request #65
Opened 2024-03-27 15:50 UTC by thinhle19

2024-03-27 18:46 UTC, oHTGo requested changes

2024-03-27 18:46 UTC, oHTGo commented on core/core-api/src/main/java/com/hbc/pms/core/api/constant/ChartConstant.java
> +          "SUM_SPECIFIC_16");
Please provide a better solution. I will help you

2024-03-28 03:46 UTC, huybui38 requested changes

2024-03-28 03:46 UTC, huybui38 commented on core/core-api/src/main/java/com/hbc/pms/core/api/constant/ChartConstant.java
> +  // TODO: find way to avoid duplicate
how about enum?

2024-03-28 03:46 UTC, huybui38 commented on core/core-api/src/main/java/com/hbc/pms/core/api/controller/v1/request/SearchMultiDayChartCommand.java
> +  }
These enum classes should not be nested in this Command class

2024-03-28 13:54 UTC, huybui38 approved these changes

2024-03-29 04:33 UTC, closed without merging